#!/bin/bash

if [[ -f /Library/Profiles/com.github.autopkg.nmcspadden-recipes.googleearthpro.mobileconfig ]]; then
	/usr/bin/profiles -I -F /Library/Profiles/com.github.autopkg.nmcspadden-recipes.googleearthpro.mobileconfig
fi